### ISSUE TITLE
Koidu tenniseväljakud

### ISSUE THREAD

**Issue by tormi** [sauevald/koidu#12]
## Idee

Rajada koostöös maaomanike, sponsorite, [Laagri Tennisekool MTÜ](https://www.teatmik.ee/et/info/80404355-Laagri-Tennisekool-MT%C3%9C) ja Saue vallaga Padula tee äärde 4 saviliivaväljakuga [nõuetele vastav](https://github.com/sauevald/koidu/files/1063322/tennisevaljak.pdf) tennisekompleks koos olme/seltsihoonega (#16). Kompleksi omanik on külaselts (#5) ja operaator tennisekool.

## Tegevused
- [x] [31.01.2017 Osapoolte 1. kohtumine](https://medium.com/koidu/koidu-tennisev%C3%A4ljakud-cf44e93067cb)
- [x] [13.02.2017 Koidu küla tennisehuviliste uuring](https://www.facebook.com/events/996474573829706/permalink/996475600496270/)
- [x] [07.03.2017 Laagri Tennisekeskuse koostatud eskiis](https://drive.google.com/open?id=0B7L2hwb4QY2UeFhYN3Q2RDhld00)
- [x] [05.04.2017 Maaomaniku projekteerimistingimuste taotlus](https://drive.google.com/open?id=0B7L2hwb4QY2UUEhIbEtPV0t6cHM) koos [täiendatud eskiisiga](https://drive.google.com/file/d/0B7L2hwb4QY2USkYwNGxlZ0p6cWM/view?usp=sharing)
- [x] [27.05.2017 Koidu küla 1. tenniseturniir](https://www.facebook.com/events/286073951818860/)
- [x] [06.2017 Saue Vallavalitsuse ja maaomaniku vaheline kokkulepe projekteerimistingimuste tagamiseks](https://github.com/sauevald/koidu/issues/12#issuecomment-311685896)
- [x] [20.06.2017 Projekteerimistingimused](https://github.com/sauevald/koidu/issues/12#issuecomment-311686355)
- [ ] [10.07-... 2017 Kändude juurimine](https://github.com/sauevald/koidu/issues/12#issuecomment-314055344)
- [x] [13.07.2017 kohtumine](https://github.com/sauevald/koidu/issues/62#issuecomment-315205190)
- [ ] Sotsiaalmaa kinnistu moodustamine (#69)
- [ ] Sotsiaalmaa kinnistu omandi üleandmine vallale
- [ ] Kinnistu kasutamise kokkulepe valla ja haldaja(te) vahel (#62)
- [ ] Finantseerimine (#63)
- [ ] Infrastruktuuri rajamine
- [ ] Ehitusloa taotlus
- [ ] Ehitusluba
- [ ] Ehitustegevus (#63)
- [ ] Haldamine

Väljakute (oranz) ja olmehoone (hall väljakute keskel) võimalik paigutus:
![tennisevaljakute muudatusettepanek rain hoone keskele](https://cloud.githubusercontent.com/assets/146800/26776118/8ef703a4-49e0-11e7-9091-bf8a2577089e.png)
https://docs.google.com/drawings/d/1B30e0XgFHTyI2ZEoM_PeA31IwgYxczdEB_WZqjG_PKo/edit?usp=sharing

![20170604_103057](https://cloud.githubusercontent.com/assets/146800/26764271/7b45f12c-496c-11e7-8ba5-c7bbb3393e1d.jpg)
![20170604_103149](https://cloud.githubusercontent.com/assets/146800/26764280/a00c9d9e-496c-11e7-8907-8c1c4be7315c.jpg)

Projekteerimistingimuste taotlusele lisatud skeem:
![tennisevaljakud-pt-taotlus](https://cloud.githubusercontent.com/assets/146800/26762259/0decf81a-4948-11e7-86b9-680bdf67e866.png)

**Comment by tormi** [comment]
> Tormi Tabor <tormi.tabor@gmail.com>
> 2. juuni 2017 13:13
> Saaja: Anti Leedu <anti@leedu.ee>, Rain Rõigas <rain.roigas@laagritennis.ee>, Kalle Pungas <Kalle.Pungas@sauevald.ee>
>  
> Tere.
>  
> Teen ettepaneku rannatennise väljakud ära jätta ning muuta tenniseplatside ja võimaliku olmehoone asukohti nii, et metsa võimalikult palju säilitada. Vastasel korral jääb metsariba liiga õhukeseks ja tuul hakkab seda laastama. Pluss külaelanike (sh minu) vastuseis metsa langetamisele.
>  
> Muudatusettepaneku skeem: 
> ![tennisevaljakute muudatusettepanek](https://cloud.githubusercontent.com/assets/146800/26764293/dc28a610-496c-11e7-929e-e48cbbdf9d78.png)
> https://docs.google.com/drawings/d/1uzVCybuLrkz6TeBE82Fv35_M4yBxbPHWPZw0YTjSzIM/edit?usp=sharing
>  
> Lisaks teen ettepaneku, et Laagri Tennisekooli MTÜ hakkab haldama kolme väljakut ja Koidu Külaselts MTÜ ühte. Loomulikult saab Tennisekool turniiride ajal ja kokkuleppel ka muul ajal kõiki nelja väljakut kasutada, aga ma ei ole leidnud hetkel paremat varianti, kuidas külaselts mängu tuua. Anti on arvanud, et saab ehk külaelanikuna ka ehitustegevusse (eelkõige platside aluse rajamisse) panustada. Külaelanikud osaleks meelsasti talgukorras platsi hooldamisel ja vajadusel ka ehitusel.
>  
> Kuidas teistel osapooltel hetkeseis on?
>  
> Palun avaldage arvamust.
>  
> Tervitades,
> Tormi Tabor

**Comment by tormi** [comment]
> Tormi Tabor <tormi.tabor@gmail.com>
> 4. juuni 2017 13:40
> 
> Tere veel.
> 
> Juhul, kui siiski on väga suur soov kunagi rannatennise platsid rajada, siis saaks need teha paarkümmend sammu üle tee: https://docs.google.com/drawings/d/1GhVKIlDqX0Xlui8knxUxF-PepguIkrBj_Ljp5X9_Kl0/edit?usp=sharing
> 
> Tervitades,
> Tormi Tabor

**Comment by tormi** [comment]
> Tormi Tabor <tormi.tabor@gmail.com>
> 4. juuni 2017 18:07
> 
> Tere veel.
> 
> Rääkisime Allar Leeduga isekeskis, et tenniseplatse teenindav hoone võiks olla samuti tennisekooli ja külaseltsi ühiskasutuses - hooajaväliselt ei ole tennisekoolil sellele nagunii kasutust. Ja ehitamise saaksime teha talgukorras - raha kuluks ainult materjalidele ja eritöödele.
> 
> Tervitades,
> Tormi Tabor

**Comment by tormi** [comment]
> 5. juuni 2017 09:12 kirjutas Rain Rõigas <rain.roigas@laagritennis.ee>:
> 
> Tere,
> 
> aitäh ettepaneku eest. Me heameelega tõstaksime klubihoone kahe väljakubloki keskele.
> 
> Head
> Rain

**Comment by tormi** [comment]
> klubihoone kahe väljakubloki keskele

> 5. juuni 2017 11:15 kirjutas Tormi Tabor <tormi.tabor@gmail.com>:
>
> Tere,
> 
> See on hea mõte!
> 
> ![tennisevaljakute muudatusettepanek rain hoone keskele](https://cloud.githubusercontent.com/assets/146800/26776118/8ef703a4-49e0-11e7-9091-bf8a2577089e.png)
> https://docs.google.com/drawings/d/1B30e0XgFHTyI2ZEoM_PeA31IwgYxczdEB_WZqjG_PKo/edit?usp=sharing
> 
> Tervitades,
> Tormi Tabor

**Comment by tormi** [comment]
Saue Vallavalitsuse ja maaomaniku vaheline kokkulepe projekteerimistingimuste tagamiseks:
- [Projekteerimistingimuste väljastamise eelkokkulepe_Vana-Kandle ja Iltre.docx](https://github.com/sauevald/koidu/files/1109128/Projekteerimistingimuste.valjastamise.eelkokkulepe_Vana-Kandle.ja.Iltre.docx)

**Comment by tormi** [comment]
### Projekteerimistingimused
![screenshot from 2017-07-10 11-49-54](https://user-images.githubusercontent.com/146800/28009955-fbff99a2-6565-11e7-9c8b-a035fc9b3f79.png)
![screenshot from 2017-07-10 11-50-07](https://user-images.githubusercontent.com/146800/28009938-f78275d4-6565-11e7-97b9-ef98ee61be1b.png)

- [Korraldus nr 464.pdf](https://github.com/sauevald/koidu/files/1109135/Korraldus.nr.464.pdf)

**Comment by tormi** [comment]
## Referents: Tähtvere Tennisekeskuse välisväljakute kompleks

Valmis juulis 2017, asub aadressil Laulupeo pst 33, Tartu. 

- Kuus täismõõtmetes saviliiva välisväljakut (savikate firmalt RedPlus, #79)
- Oranži palli miniväljak (kunstmuruväljak)
- Klubihoone 
- Tennisepood ja keelestamine
- Kohvik
- Riietusruumid koos saunaga
- Klubiruumid

![zf_dji_0136](https://user-images.githubusercontent.com/146800/28003713-556856aa-6548-11e7-8ffa-a6b09b83db60.jpg)
![zf_dji_0134](https://user-images.githubusercontent.com/146800/28003714-5568adf8-6548-11e7-94e1-ec5882a7773b.jpg)
![20170525_134856-768x576 1](https://user-images.githubusercontent.com/146800/28006718-323c3492-6559-11e7-8ba9-5bab2c72096f.jpg)

FOTOD: http://tartutennis.ee/uudised/valisvaljakute-avamine-08-07-2017/

**Comment by tormi** [comment]
Täna tehakse algust kändude juurimisega kinnistul:
![20170710_122756](https://user-images.githubusercontent.com/146800/28011762-216c4e46-656c-11e7-86fa-5562d0e8883c.jpg)

**Comment by tormi** [comment]
![20170716_193742](https://user-images.githubusercontent.com/146800/28271207-97a5695e-6b10-11e7-9c5a-2dc16fda0972.jpg)
